//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Fournisseurs : global::System.Configuration.ApplicationSettingsBase {
        
        private static Fournisseurs defaultInstance = ((Fournisseurs)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Fournisseurs())));
        
        public static Fournisseurs Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Administrateur\\Desktop\\Ani-Forme\\fournisseurs.txt")]
        public string Chemin {
            get {
                return ((string)(this["Chemin"]));
            }
            set {
                this["Chemin"] = value;
            }
        }
    }
}
